{% set name = "snpio" %}
{% set version = "1.2.2" %}
{% set license = "GPL-3.0-or-later" %}
{% set github_url = "https://github.com/btmartin721/SNPio" %}

package:
    name: {{ name|lower }}
    version: "{{ version }}"

source:
    git_rev: v{{ version }}
    git_url: {{ github_url }}

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python

requirements:
    build:
        - python >=3.11,<3.13
        - setuptools
        - wheel
        - pip
    host:
        - python >=3.11,<3.13
        - pip
    run:
        - python >=3.11,<3.13
        - bokeh
        - h5py
        - holoviews
        - python-kaleido
        - kneed
        - matplotlib
        - numpy
        - pandas
        - panel
        - plotly
        - pysam  # Available in bioconda
        - requests
        - scikit-learn
        - scipy
        - statsmodels
        - seaborn
        - toytree  # Available in conda-forge
        - tqdm

test:
    imports:
        - snpio

about:
    home: {{ github_url }}
    license: {{ license }}
    license_family: GPL
    license_file: LICENSE
    summary: "SNPio is a Python API for population genetic file processing, filtering, and analysis. SNPio is designed to be a user-friendly tool for the manipulation of population genetic data in a variety of formats, including VCF, PHYLIP, and STRUCTURE files. SNPio can be used to filter data based on missing data, minor allele frequency, singletons, and monomorphic sites. SNPio can also be used to convert between file formats, and to generate summary statistics for population genetic analyses. SNPio is designed to be a flexible and user-friendly tool for the analysis of population genetic data."
    dev_url: {{ github_url }}
    doc_url: https://snpio.readthedocs.io/en/latest/

extra:
    recipe-maintainers:
        - btmartin721
