{% set name = "snpio" %}
{% set version = "1.6.4" %}
{% set license = "GPL-3.0-or-later" %}
{% set github_url = "https://github.com/btmartin721/SNPio" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  git_url: {{ github_url }}
  git_rev: v{{ version }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.11,<3.13
    - pip
    - setuptools
    - wheel
    - requests >=2.9.1,<2.30.0a0
    - conda-build
    - anaconda-client
  host:
    - python >=3.11,<3.13
    - pip
  run:
    - python >=3.11,<3.13
    - pysam >=0.22.0
    - bokeh
    - h5py
    - holoviews
    - python-kaleido
    - kneed
    - matplotlib
    - multiqc >=1.29
    - numba >=0.61.2
    - numpy
    - pandas
    - panel
    - plotly
    - requests
    - scikit-learn
    - scipy
    - statsmodels
    - seaborn
    - toytree
    - tqdm

about:
  home: {{ github_url }}
  license: {{ license }}
  license_family: GPL
  license_file: LICENSE
  summary: "SNPio is a Python API for population genetic file processing, filtering, and analysis. It is designed to be a user-friendly tool for the manipulation of population genetic data in a variety of formats. SNPio can be used to filter data based on missingness, MAF and MAC, singletons, biallelic, and monomorphic sites. It can also generate summary statistics for population genetic analyses."
  dev_url: {{ github_url }}
  doc_url: https://snpio.readthedocs.io/en/latest/
  keywords:
    - population genetics
    - SNPs
    - bioinformatics
    - genomics
    - machine learning
  authors:
    - "Bradley T. Martin <evobio721@gmail.com>"
    - "Tyler K. Chafin <tylerkchafin@gmail.com>"

extra:
  recipe-maintainers:
    - btmartin721