{% set name = "snpio" %}
{% set version = "1.2.18" %}
{% set license = "GPL-3.0-or-later" %}
{% set github_url = "https://github.com/btmartin721/SNPio" %}
{% set use_local = environ.get("CI", False) %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
{% if use_local %}
  path: ../
{% else %}
  git_url: {{ github_url }}
  git_rev: v{{ version }}
{% endif %}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [python_impl != "cpython"]

requirements:
  build:
    - python >=3.11,<3.14
    - pip
    - setuptools
    - wheel
    - gcc
  host:
    - python >=3.11,<3.14
    - pip
    - pysam >=0.23.0
  run:
    - python >=3.11,<3.14
    - pysam >=0.23.0
    - bokeh
    - h5py
    - holoviews
    - python-kaleido
    - kneed
    - matplotlib
    - numpy
    - pandas
    - panel
    - plotly
    - requests
    - scikit-learn
    - scipy
    - statsmodels
    - seaborn
    - toytree
    - tqdm

test:
  imports:
    - snpio

about:
  home: {{ github_url }}
  license: {{ license }}
  license_family: GPL
  license_file: LICENSE
  summary: "SNPio is a Python API for population genetic file processing, filtering, and analysis. It is designed to be a user-friendly tool for the manipulation of population genetic data in a variety of formats. SNPio can be used to filter data based on missingness, MAF and MAC, singletons, biallelic, and monomorphic sites. It can also generate summary statistics for population genetic analyses."
  dev_url: {{ github_url }}
  doc_url: https://snpio.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - btmartin721
