mode: Mainline
commit-message-incrementing: Enabled
branches:
  main:
    regex: ^main$
    increment: Minor
    is-release-branch: true
    prevent-increment-of-merged-branch-version: false
    tag: ""
  master:
    regex: ^master$
    increment: Minor
    is-release-branch: true
    prevent-increment-of-merged-branch-version: false
    tag: ""
ignore:
  sha: []
