default_stages: [push]

repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest with full Conda context
        entry: ./scripts/run_tests.sh
        language: script
        pass_filenames: false
        stages: [push]
