default_stages: [push]

repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest before push
        entry: pytest tests/
        language: system
        pass_filenames: false
        stages: [push]
