repos:
  - repo: local
    hooks:
      - id: pytest-runner
        name: Run pytest
        entry: pytest tests/
        language: python
        types: [python]
        additional_dependencies: [snpio, pytest]
        pass_filenames: false
