repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest
        entry: ./scripts/run_tests.sh
        language: script
        pass_filenames: false
        stages: [pre-push]

      - id: update-versioning
        name: Update version number
        entry: python scripts/update_metadata.py # path to script from repo root
        language: python
        stages: [pre-commit]
        additional_dependencies:
          - pyyaml
          - pytest

      - id: amend-commit-1
        name: Amend commit with version number
        entry: scripts/create_commit_flag.sh
        language: script
        stages: [pre-commit]

      - id: amend-commit-2
        name: Amend commit with version number
        entry: scripts/amend_commit_hook.sh
        language: script
        stages: [post-commit]
