repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest
        entry: ./scripts/run_tests.sh
        language: script
        pass_filenames: false
        stages: [pre-push]
