default_stages: [push]

repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest in snpio-dev conda env
        entry: bash -c "source /opt/anaconda3/etc/profile.d/conda.sh && conda activate snpio-dev && pytest tests/"
        language: system
        pass_filenames: false
        types: [python]
