repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest
        entry: ./scripts/run_tests.sh
        language: script
        pass_filenames: false
        stages: [pre-push]

      - id: update-versioning
        name: Update version number
        entry: python scripts/update_metadata.py # path to script from repo root
        language: python
        stages: [pre-commit]
        additional_dependencies:
          - pyyaml
          - pytest

      # - id: create-user-manual
      #   name: Create User Manual
      #   entry: scripts/create_user_manual.sh # path to script from repo root
      #   language: script
      #   stages: [pre-commit]
