repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest before push
        entry: zsh -c "source .snpio-dev/bin/activate && pytest tests/"
        language: system
        pass_filenames: false
        stages: [push]
