name: snpio-dev
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python >=3.11,<3.14
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - scikit-learn
  - scipy
  - h5py
  - requests
  - pysam >=0.23.0
  - plotly
  - bokeh
  - holoviews
  - python-kaleido
  - panel
  - kneed
  - statsmodels
  - toytree
  - pytz
  - pip:
      - -e .[dev]
