title: "SNPio MultiQC Report"
subtitle: "Results from an analysis using the SNPio Python API"
custom_logo: "snpio/img/snpio_logo.png"
custom_logo_url: "https://github.com/btmartin721/SNPio/blob/master/snpio/img/snpio_logo.png"
custom_logo_title: "SNPio: A Python API for Population Genomics"
max_table_rows: 2000

# -----------------------------------------------------------------------------
# Section order
# -----------------------------------------------------------------------------
report_section_order:
  overview: 1
  filtering: 2
  missing_data: 3
  population_structure: 4
  genetic_differentiation: 5
  introgression: 6
  detailed_statistics: 7
  outliers: 8
  benchmarking: 9
  logs: 10

# -----------------------------------------------------------------------------
# Assign panels to sections
# -----------------------------------------------------------------------------
parent_ids:
  # Overview
  population_counts: overview
  genotype_distribution: overview
  summary_statistics: overview
  allele_summary: overview

  # Missing Data
  missing_summary: missing_data
  missingness_report: missing_data
  individual_missingness: missing_data
  locus_missingness: missing_data
  population_missingness: missing_data
  population_locus_missingness: missing_data

  # Filtering
  sankey_html: filtering
  filtering_results_combined: filtering
  filtering_results_missing_loci_samples_plotly: filtering
  filtering_results_missing_population_plotly: filtering
  mac_thresholds: filtering
  maf_thresholds: filtering
  boolean_thresholds: filtering

  # Population Structure
  pca_missingness: population_structure
  pca_missingness_scatter: population_structure

  # Genetic Differentiation (updated Fst panel IDs)
  wc_fst_observed: genetic_differentiation
  wc_fst_bootstrap_mean: genetic_differentiation
  wc_fst_bootstrap_ci95: genetic_differentiation
  wc_fst_permutation_observed: genetic_differentiation
  wc_fst_permutation_pvalues: genetic_differentiation

  nei_observed: genetic_differentiation
  nei_permutation_observed: genetic_differentiation
  nei_permutation_pvalues: genetic_differentiation
  nei_bootstrap_mean: genetic_differentiation
  nei_bootstrap_ci95: genetic_differentiation

  pairwise_nei_distances: genetic_differentiation
  pairwise_nei_distance_pvalues: genetic_differentiation
  pairwise_nei_distance_ci95: genetic_differentiation

  # Introgression: Patterson's D
  d_statistics_heatmap_patterson: introgression
  d_statistics_significance_counts_table_patterson: introgression
  d_statistics_significance_counts_plot_patterson: introgression
  dstat_stacked_significance_barplot_patterson: introgression
  d_statistics_z_distribution_patterson_d: introgression
  dstat_pvalue_distribution_patterson: introgression
  dstat_chi_square_distribution_patterson: introgression

  # Introgression: Partitioned D
  d_statistics_heatmap_partitioned: introgression
  d_statistics_significance_counts_table_partitioned: introgression
  d_statistics_significance_counts_plot_partitioned: introgression
  dstat_stacked_significance_barplot_partitioned: introgression
  d_statistics_z_distribution_partitioned_D1: introgression
  d_statistics_z_distribution_partitioned_D2: introgression
  d_statistics_z_distribution_partitioned_D12: introgression
  dstat_pvalue_distribution_partitioned: introgression
  dstat_chi_square_distribution_partitioned: introgression

  # Introgression: DFOIL D
  d_statistics_heatmap_dfoil: introgression
  d_statistics_significance_counts_table_dfoil: introgression
  d_statistics_significance_counts_plot_dfoil: introgression
  dstat_stacked_significance_barplot_dfoil: introgression
  d_statistics_z_distribution_dfoil_DFO: introgression
  d_statistics_z_distribution_dfoil_DIL: introgression
  d_statistics_z_distribution_dfoil_DFI: introgression
  d_statistics_z_distribution_dfoil_DOL: introgression
  dstat_pvalue_distribution_dfoil: introgression
  dstat_chi_square_distribution_dfoil: introgression

  # Detailed Stats
  summary_statistics_overall: detailed_statistics
  summary_statistics_per_population_pi: detailed_statistics
  summary_statistics_per_population_ho: detailed_statistics
  summary_statistics_per_population_he: detailed_statistics

  # Outliers
  fst_outliers_dbscan_method: outliers
  fst_outliers_permutation_method: outliers

  # Logs
  verbose: logs
  debug: logs

# -----------------------------------------------------------------------------
# Section and panel titles
# -----------------------------------------------------------------------------
section_names:
  overview: "Overview"
  missing_data: "Missing Data"
  filtering: "Filtering"
  population_structure: "Population Structure"
  genetic_differentiation: "Genetic Differentiation"
  introgression: "Introgression"
  detailed_statistics: "Diversity Statistics"
  outliers: "Outlier Detection"
  logs: "Logs & Diagnostics"

  population_counts: "Population Counts"
  genotype_distribution: "Genotype Distribution"
  summary_statistics: "Summary Stats"
  allele_summary: "Allele Summary"

  missing_summary: "Missing Data Summary"
  missingness_report: "Missingness Report"
  individual_missingness: "Missing by Individual"
  locus_missingness: "Missing by Locus"
  population_missingness: "Missing by Population"
  population_locus_missingness: "Missing by Pop x Locus"

  sankey_html: "Sankey Filtering Report"
  filtering_results_combined: "Filtering Results Table"
  filtering_results_missing_loci_samples_plotly: "Missingness Per-locus and Per-Sample"
  filtering_results_missing_population_plotly: "Missingness Per-locus and Per-Population"
  mac_thresholds: "MAC Thresholds"
  maf_thresholds: "MAF Thresholds"
  boolean_thresholds: "Boolean Thresholds (Singletons, Monomorphic, Biallelic)"

  pca_missingness: "PCA Results Table"
  pca_missingness_scatter: "PCA Scatter Plot"

  # Updated Fst titles
  wc_fst_observed: "Fst (Weir & Cockerham) — Observed"
  wc_fst_bootstrap_mean: "Fst (Weir & Cockerham) — Bootstrap Mean"
  wc_fst_bootstrap_ci95: "Fst (Weir & Cockerham) — 95% CIs (Bootstrap)"
  wc_fst_permutation_observed: "Fst (Weir & Cockerham) — Observed (Permutation Test)"
  wc_fst_permutation_pvalues: "Fst (Weir & Cockerham) — Permutation P-values"

  nei_observed: "Nei's Genetic Distance — Observed"
  nei_permutation_observed: "Nei's Genetic Distance — Observed (Permutation)"
  nei_permutation_pvalues: "Nei's Genetic Distance — Permutation P-values"
  nei_bootstrap_mean: "Nei's Genetic Distance — Bootstrap Mean"
  nei_bootstrap_ci95: "Nei's Genetic Distance — 95% CIs (Bootstrap)"

  pairwise_nei_distances: "Nei Distances"
  pairwise_nei_distance_pvalues: "Nei Distance P-values"
  pairwise_nei_distance_ci95: "Nei's Genetic Distance 95% CIs"

  # Patterson D
  d_statistics_heatmap_patterson: "Patterson D: Heatmap"
  d_statistics_significance_counts_table_patterson: "Patterson D: Significance Counts (Table)"
  d_statistics_significance_counts_plot_patterson: "Patterson D: Significance Counts (Plot)"
  dstat_stacked_significance_barplot_patterson: "Patterson D: Significance Breakdown"
  d_statistics_z_distribution_patterson_d: "Patterson D: Z-Score Distribution"
  dstat_pvalue_distribution_patterson: "Patterson D: P-value Distribution"
  dstat_chi_square_distribution_patterson: "Patterson D: Chi-Square Distribution"

  # Partitioned D
  d_statistics_heatmap_partitioned: "Partitioned D: Heatmap"
  d_statistics_significance_counts_table_partitioned: "Partitioned D: Significance Counts (Table)"
  d_statistics_significance_counts_plot_partitioned: "Partitioned D: Significance Counts (Plot)"
  dstat_stacked_significance_barplot_partitioned: "Partitioned D: Significance Breakdown"
  d_statistics_z_distribution_partitioned_D1: "Partitioned D: D1 Z-Score Distribution"
  d_statistics_z_distribution_partitioned_D2: "Partitioned D: D2 Z-Score Distribution"
  d_statistics_z_distribution_partitioned_D12: "Partitioned D: D12 Z-Score Distribution"
  dstat_pvalue_distribution_partitioned: "Partitioned D: P-value Distribution"
  dstat_chi_square_distribution_partitioned: "Partitioned D: Chi-Square Distribution"

  # DFOIL D
  d_statistics_heatmap_dfoil: "DFOIL D: Heatmap"
  d_statistics_significance_counts_table_dfoil: "DFOIL D: Significance Counts (Table)"
  d_statistics_significance_counts_plot_dfoil: "DFOIL D: Significance Counts (Plot)"
  dstat_stacked_significance_barplot_dfoil: "DFOIL D: Significance Breakdown"
  d_statistics_z_distribution_dfoil_DFO: "DFOIL D: DFO Z-Score Distribution"
  d_statistics_z_distribution_dfoil_DIL: "DFOIL D: DIL Z-Score Distribution"
  d_statistics_z_distribution_dfoil_DFI: "DFOIL D: DFI Z-Score Distribution"
  d_statistics_z_distribution_dfoil_DOL: "DFOIL D: DOL Z-Score Distribution"
  dstat_pvalue_distribution_dfoil: "DFOIL D: P-value Distribution"
  dstat_chi_square_distribution_dfoil: "DFOIL D: Chi-Square Distribution"

  # Detailed Stats
  summary_statistics_overall: "Overall Summary"
  summary_statistics_per_population_pi: "Pi per Population"
  summary_statistics_per_population_ho: "Ho per Population"
  summary_statistics_per_population_he: "He per Population"

  # Outliers
  fst_outliers_dbscan_method: "Fst Outliers: DBSCAN"
  fst_outliers_permutation_method: "Fst Outliers: Permutation"

  # Logs
  verbose: "Verbose Logs"
  debug: "Debug Logs"

# -----------------------------------------------------------------------------
# Section descriptions
# -----------------------------------------------------------------------------
section_descriptions:
  overview: "Summary tables of population-level and genotype data."
  missing_data: "Plots and tables showing missing genotype patterns."
  filtering: "Threshold-based SNP and sample filtering summaries."
  population_structure: "PCA results for structure and missingness bias."
  genetic_differentiation: "Pairwise Fst and Nei distance measures."
  introgression: "ABBA-BABA tests for gene flow detection."
  detailed_statistics: "Genetic diversity and heterozygosity summaries."
  outliers: "Fst outlier SNPs identified via clustering or permutation."
  logs: "Diagnostic logs from SNPio run."

# -----------------------------------------------------------------------------
# Remove sections from final report
# -----------------------------------------------------------------------------
remove_sections:
  - verbose
  - debug
