title: "SNPio MultiQC Report"
subtitle: "Results from an analysis using the SNPio Python API"
custom_logo: "snpio/img/snpio_logo.png"
custom_logo_url: "https://github.com/btmartin721/SNPio/blob/master/snpio/img/snpio_logo.png"
custom_logo_title: "SNPio: A Python API for Population Genomics"
max_table_rows: 2000

# -----------------------------------------------------------------------------
# Section order
# -----------------------------------------------------------------------------
report_section_order:
  overview: 1
  filtering: 2
  missing_data: 3
  population_structure: 4
  genetic_differentiation: 5
  introgression: 6
  detailed_statistics: 7
  outliers: 8
  benchmarking: 9
  logs: 10

# -----------------------------------------------------------------------------
# Assign panels to sections
# -----------------------------------------------------------------------------
parent_ids:
  # Overview
  population_counts: overview
  genotype_distribution: overview
  summary_statistics: overview
  allele_summary: overview

  # Missing Data
  missing_summary: missing_data
  missingness_report: missing_data
  individual_missingness: missing_data
  locus_missingness: missing_data
  population_missingness: missing_data
  population_locus_missingness: missing_data

  # Filtering
  sankey_html: filtering
  filtering_results_combined: filtering
  filtering_results_missing_loci_samples_plotly: filtering
  filtering_results_missing_population_plotly: filtering
  mac_thresholds: filtering
  maf_thresholds: filtering
  boolean_thresholds: filtering

  # Population Structure
  pca_missingness: population_structure
  pca_missingness_scatter: population_structure

  # Genetic Differentiation
  pairwise_WC_fst: genetic_differentiation
  pairwise_WC_fst_ci95: genetic_differentiation
  pairwise_WC_fst_pvalues: genetic_differentiation
  pairwise_nei_distances: genetic_differentiation
  pairwise_nei_distance_pvalues: genetic_differentiation

  # Introgression
  d_statistics_significance_counts_patterson: introgression
  dstat_chi_square_distribution_patterson: introgression
  dstat_pvalue_distribution_patterson: introgression
  dstat_stacked_significance_barplot_patterson: introgression
  dstat_upset_style_significance_counts_patterson: introgression
  d_statistics_heatmap_patterson: introgression

  d_statistics_significance_counts_partitioned: introgression
  dstat_chi_square_distribution_partitioned: introgression
  dstat_pvalue_distribution_partitioned: introgression
  dstat_stacked_significance_barplot_partitioned: introgression
  dstat_upset_style_significance_counts_partitioned: introgression
  d_statistics_heatmap_partitioned: introgression

  d_statistics_significance_counts_dfoil: introgression
  dstat_chi_square_distribution_dfoil: introgression
  dstat_pvalue_distribution_dfoil: introgression
  dstat_stacked_significance_barplot_dfoil: introgression
  dstat_upset_style_significance_counts_dfoil: introgression
  d_statistics_heatmap_dfoil: introgression

  # Detailed Stats
  summary_statistics_overall: detailed_statistics
  summary_statistics_per_population_pi: detailed_statistics
  summary_statistics_per_population_ho: detailed_statistics
  summary_statistics_per_population_he: detailed_statistics

  # Outliers
  fst_outliers_dbscan_method: outliers
  fst_outliers_permutation_method: outliers

  # Logs
  verbose: logs
  debug: logs

# -----------------------------------------------------------------------------
# Section and panel titles
# -----------------------------------------------------------------------------
section_names:
  overview: "Overview"
  missing_data: "Missing Data"
  filtering: "Filtering"
  population_structure: "Population Structure"
  genetic_differentiation: "Genetic Differentiation"
  introgression: "Introgression"
  detailed_statistics: "Diversity Statistics"
  outliers: "Outlier Detection"
  logs: "Logs & Diagnostics"

  population_counts: "Population Counts"
  genotype_distribution: "Genotype Distribution"
  summary_statistics: "Summary Stats"
  allele_summary: "Allele Summary"

  missing_summary: "Missing Data Summary"
  missingness_report: "Missingness Report"
  individual_missingness: "Missing by Individual"
  locus_missingness: "Missing by Locus"
  population_missingness: "Missing by Population"
  population_locus_missingness: "Missing by Pop x Locus"

  sankey_html: "Sankey Filtering Report"
  filtering_results_combined: "Filtering Results Table"
  filtering_results_missing_loci_samples_plotly: "Missingness Per-locus and Per-Sample"
  filtering_results_missing_population_plotly: "Missingness Per-locus and Per-Population"
  mac_thresholds: "MAC Thresholds"
  maf_thresholds: "MAF Thresholds"
  boolean_thresholds: "Boolean Thresholds (Singletons, Monomorphic, Biallelic)"

  pca_missingness: "PCA Results"
  pca_missingness_scatter: "PCA: Missingness Colored"

  pairwise_WC_fst: "Fst (Weir & Cockerham)"
  pairwise_WC_fst_ci95: "Fst 95% CI"
  pairwise_WC_fst_pvalues: "Fst P-values"
  pairwise_nei_distances: "Nei Distances"
  pairwise_nei_distance_pvalues: "Nei Distance P-values"

  d_statistics_heatmap_patterson: "Patterson D: Heatmap"
  d_statistics_heatmap_partitioned: "Partitioned D: Heatmap"
  d_statistics_heatmap_dfoil: "DFOIL D: Heatmap"

  dstat_chi_square_distribution_patterson: "Patterson D: Chi-Square"
  dstat_chi_square_distribution_partitioned: "Partitioned D: Chi-Square"
  dstat_chi_square_distribution_dfoil: "DFOIL D: Chi-Square"

  dstat_pvalue_distribution_patterson: "Patterson D: P-values"
  dstat_pvalue_distribution_partitioned: "Partitioned D: P-values"
  dstat_pvalue_distribution_dfoil: "DFOIL D: P-values"

  dstat_stacked_significance_barplot_patterson: "Patterson D: Significance Breakdown"
  dstat_stacked_significance_barplot_partitioned: "Partitioned D: Significance Breakdown"
  dstat_stacked_significance_barplot_dfoil: "DFOIL D: Significance Breakdown"

  d_statistics_significance_counts_patterson: "Patterson D: Significant Tests"
  d_statistics_significance_counts_partitioned: "Partitioned D: Significant Tests"
  d_statistics_significance_counts_dfoil: "DFOIL D: Significant Tests"

  dstat_upset_style_significance_counts_patterson: "Patterson D: UpSet Plot"
  dstat_upset_style_significance_counts_partitioned: "Partitioned D: UpSet Plot"
  dstat_upset_style_significance_counts_dfoil: "DFOIL D: UpSet Plot"

  summary_statistics_overall: "Overall Summary"
  summary_statistics_per_population_pi: "Pi per Population"
  summary_statistics_per_population_ho: "Ho per Population"
  summary_statistics_per_population_he: "He per Population"

  fst_outliers_dbscan_method: "Fst Outliers: DBSCAN"
  fst_outliers_permutation_method: "Fst Outliers: Permutation"

  verbose: "Verbose Logs"
  debug: "Debug Logs"

# -----------------------------------------------------------------------------
# Section descriptions (if supported)
# -----------------------------------------------------------------------------
section_descriptions:
  overview: "Summary tables of population-level and genotype data."
  missing_data: "Plots and tables showing missing genotype patterns."
  filtering: "Threshold-based SNP and sample filtering summaries."
  population_structure: "PCA results for structure and missingness bias."
  genetic_differentiation: "Pairwise Fst and Nei distance measures."
  introgression: "ABBA-BABA tests for gene flow detection."
  detailed_statistics: "Genetic diversity and heterozygosity summaries."
  outliers: "Fst outlier SNPs identified via clustering or permutation."
  logs: "Diagnostic logs from SNPio run."

# -----------------------------------------------------------------------------
# Remove sections from final report
# -----------------------------------------------------------------------------
remove_sections:
  - verbose
  - debug
