r"""Independent validation oracles for unbiased unphased LD estimation.

The functions in this module do not participate in production LD analyses.
They provide three complementary checks:

1. exact expectations under a multinomial sampling model;
2. regression against a committed corpus generated by the paper authors' ``moments-popgen`` implementation; and
3. summaries for published-data and locus-pair convergence benchmarks.

The exact oracle enumerates every possible nine-state genotype count vector
for small samples and compares the estimator's expected value with the
population-level LD formulas. This validates finite-sample unbiasedness without
using ``moments-popgen`` or reusing SNPio's polynomial coefficients.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from importlib.resources import files
from itertools import combinations
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd
from scipy.special import gammaln

from snpio.popgenstats.ld_polynomials import evaluate_unbiased_ld

STATISTICS: Final[tuple[str, ...]] = ("D", "D2", "Dz", "pi2")
COUNT_COLUMNS: Final[tuple[str, ...]] = tuple(f"n{index}" for index in range(1, 10))

DEFAULT_HAPLOTYPE_SCENARIOS: Final[dict[str, tuple[float, float, float, float]]] = {
    "linkage_equilibrium": (0.42, 0.28, 0.18, 0.12),
    "positive_ld": (0.55, 0.10, 0.10, 0.25),
    "negative_ld": (0.10, 0.45, 0.35, 0.10),
    "asymmetric_ld": (0.62, 0.08, 0.22, 0.08),
}
"""Haplotype frequencies ordered as ``AB, Ab, aB, ab``."""

PUBLISHED_ISLAND_FOX_ESTIMATES: Final[pd.DataFrame] = pd.DataFrame(
    {
        "Population": [
            "San Miguel I",
            "Santa Rosa I",
            "Santa Cruz I",
            "Santa Catalina I",
            "San Clemente I",
            "San Nicolas I",
        ],
        "Published_Ne": [15.3, 13.3, 22.8, 40.9, 59.1, 13.8],
        "Published_Ne_CI_Lower": [14.5, 13.0, 22.4, 40.4, 53.0, 13.0],
        "Published_Ne_CI_Upper": [16.1, 13.6, 23.3, 41.6, 66.7, 15.2],
    }
)
"""Ragsdale and Gravel (2020), table 1, 90% bootstrap intervals."""


def validation_data_path(filename: str) -> Path:
    """Resolve a packaged LD validation data file."""

    return Path(str(files("snpio.validation").joinpath("data", filename)))


def prepare_island_fox_genepop(
    genepop: str | Path, directory: str | Path
) -> tuple[Path, Path]:
    """Assign unique sample IDs to the six-section Dryad GenePop benchmark.

    The published file repeats the island code as every sample ID within a
    population. SNPio requires unique sample IDs when applying a population
    map, so this validation-only normalization preserves all genotype calls
    while assigning ``SMI_001``, ``SMI_002``, and analogous identifiers.
    """

    source = Path(genepop)
    destination = Path(directory)
    labels = ("SMI", "SRI", "SCI", "SCA", "SCL", "SNI")
    population_index = -1
    population_sample = 0
    normalized_rows = []
    popmap_rows = []
    seen_data = False
    for raw_line in source.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.upper() == "POP":
            seen_data = True
            population_index += 1
            population_sample = 0
            if population_index >= len(labels):
                raise ValueError("GenePop file contains more than six POP sections.")
            normalized_rows.append("POP")
            continue
        if seen_data:
            if population_index < 0 or "," not in line:
                raise ValueError("Malformed GenePop sample row in published benchmark.")
            population_sample += 1
            sample_id = f"{labels[population_index]}_{population_sample:03d}"
            genotype_calls = line.split(",", maxsplit=1)[1].strip()
            normalized_rows.append(f"{sample_id}, {genotype_calls}")
            popmap_rows.append(f"{sample_id}\t{labels[population_index]}")
        else:
            normalized_rows.append(line)
    if population_index + 1 != len(labels):
        raise ValueError(
            f"Expected six GenePop POP sections, observed {population_index + 1}."
        )
    destination.mkdir(parents=True, exist_ok=True)
    normalized = destination / "GP_NO_grays_unique_ids.txt"
    popmap = destination / "island_fox.popmap"
    normalized.write_text("\n".join(normalized_rows) + "\n", encoding="utf-8")
    popmap.write_text("\n".join(popmap_rows) + "\n", encoding="utf-8")
    return normalized, popmap


def _normalized_probabilities(
    probabilities: np.ndarray | tuple[float, float, float, float],
    *,
    expected_size: int,
    name: str,
) -> np.ndarray:
    """Validate and normalize a probability vector within floating tolerance."""

    values = np.asarray(probabilities, dtype=np.float64)
    if values.shape != (expected_size,):
        raise ValueError(f"{name} must contain exactly {expected_size} values.")
    if not np.all(np.isfinite(values)) or np.any(values < 0.0):
        raise ValueError(f"{name} must contain finite non-negative values.")
    total = float(values.sum())
    if total <= 0.0 or not np.isclose(total, 1.0, rtol=0.0, atol=1e-12):
        raise ValueError(f"{name} must sum to one; observed {total:.16g}.")
    return values / total


def genotype_probabilities_from_haplotypes(
    haplotype_frequencies: np.ndarray | tuple[float, float, float, float],
) -> np.ndarray | tuple[float, float, float, float]:
    """Return nine unphased diploid genotype probabilities under random union.

    Haplotype frequencies use the order ``AB, Ab, aB, ab``. Genotype
    probabilities use SNPio's order ``AABB, AABb, AAbb, AaBB, AaBb, Aabb,
    aaBB, aaBb, aabb``.
    """

    ab_major, ab_right, ab_left, ab_minor = _normalized_probabilities(
        haplotype_frequencies,
        expected_size=4,
        name="haplotype_frequencies",
    )
    return np.asarray(
        [
            ab_major**2,
            2.0 * ab_major * ab_right,
            ab_right**2,
            2.0 * ab_major * ab_left,
            2.0 * (ab_major * ab_minor + ab_right * ab_left),
            2.0 * ab_right * ab_minor,
            ab_left**2,
            2.0 * ab_left * ab_minor,
            ab_minor**2,
        ],
        dtype=np.float64,
    )


def population_ld_statistics(
    genotype_probabilities: np.ndarray | tuple[float, float, float, float],
) -> dict[str, float]:
    """Calculate population LD targets directly from genotype probabilities.

    This is a formula-level oracle independent of the sparse polynomial term
    builder and finite-sample evaluator used by production SNPio code.
    """

    g = _normalized_probabilities(
        genotype_probabilities,
        expected_size=9,
        name="genotype_probabilities",
    )
    x_ab_major = g[0] + 0.5 * g[1] + 0.5 * g[3] + 0.25 * g[4]
    x_ab_right = g[2] + 0.5 * g[1] + 0.5 * g[5] + 0.25 * g[4]
    x_ab_left = g[6] + 0.5 * g[3] + 0.5 * g[7] + 0.25 * g[4]
    x_ab_minor = g[8] + 0.5 * g[5] + 0.5 * g[7] + 0.25 * g[4]

    delta = x_ab_major * x_ab_minor - x_ab_right * x_ab_left
    left_major = x_ab_major + x_ab_right
    left_minor = x_ab_left + x_ab_minor
    right_major = x_ab_major + x_ab_left
    right_minor = x_ab_right + x_ab_minor
    return {
        "D": 2.0 * delta,
        "D2": 4.0 * delta**2,
        "Dz": 2.0 * delta * (left_minor - left_major) * (right_minor - right_major),
        "pi2": left_major * left_minor * right_major * right_minor,
    }


def enumerate_count_vectors(sample_size: int, n_states: int = 9) -> np.ndarray:
    """Enumerate all weak compositions of ``sample_size`` into ``n_states``."""

    if sample_size < 0:
        raise ValueError("sample_size must be non-negative.")
    if n_states < 1:
        raise ValueError("n_states must be positive.")
    if n_states == 1:
        return np.asarray([[sample_size]], dtype=np.int64)

    rows = []
    for dividers in combinations(range(sample_size + n_states - 1), n_states - 1):
        boundaries = (-1, *dividers, sample_size + n_states - 1)
        rows.append(
            [boundaries[index + 1] - boundaries[index] - 1 for index in range(n_states)]
        )
    return np.asarray(rows, dtype=np.int64)


def _multinomial_probabilities(
    counts: np.ndarray, genotype_probabilities: np.ndarray
) -> np.ndarray:
    """Calculate stable multinomial probabilities, including zero-probability states."""

    sample_size = counts.sum(axis=1)
    log_probabilities = gammaln(sample_size + 1.0) - gammaln(counts + 1.0).sum(axis=1)
    positive = genotype_probabilities > 0.0
    if np.any(~positive):
        impossible = np.any(counts[:, ~positive] > 0, axis=1)
    else:
        impossible = np.zeros(counts.shape[0], dtype=bool)
    if np.any(positive):
        log_terms = np.log(genotype_probabilities[positive])
        log_probabilities += np.sum(counts[:, positive] * log_terms[None, :], axis=1)
    probabilities = np.exp(log_probabilities)
    probabilities[impossible] = 0.0
    return probabilities


def exact_multinomial_expectation(
    genotype_probabilities: np.ndarray | tuple[float, float, float, float],
    sample_size: int,
) -> dict[str, float]:
    """Integrate SNPio LD estimates over every multinomial sample outcome."""

    if sample_size < 4:
        raise ValueError("sample_size must be at least four for all LD statistics.")
    probabilities = _normalized_probabilities(
        genotype_probabilities,
        expected_size=9,
        name="genotype_probabilities",
    )
    counts = enumerate_count_vectors(sample_size)
    weights = _multinomial_probabilities(counts, probabilities)
    if not np.isclose(weights.sum(), 1.0, rtol=0.0, atol=5e-13):
        raise RuntimeError("Enumerated multinomial probabilities do not sum to one.")
    estimates = evaluate_unbiased_ld(counts)
    return {
        statistic: float(np.dot(weights, estimates[statistic]))
        for statistic in STATISTICS
    }


def validate_exact_expectations(
    *,
    sample_sizes: Iterable[int] = (4, 6),
    scenarios: (
        Mapping[str, np.ndarray | tuple[float, float, float, float]] | None
    ) = None,
    atol: float = 1e-12,
) -> pd.DataFrame:
    """Validate exact finite-sample unbiasedness across reference scenarios."""

    scenario_map = DEFAULT_HAPLOTYPE_SCENARIOS if scenarios is None else scenarios
    rows: list[dict[str, float | int | str | bool]] = []
    for scenario, haplotypes in scenario_map.items():
        probabilities = genotype_probabilities_from_haplotypes(haplotypes)
        target = population_ld_statistics(probabilities)
        for sample_size in sample_sizes:
            observed = exact_multinomial_expectation(probabilities, sample_size)
            for statistic in STATISTICS:
                error = abs(observed[statistic] - target[statistic])
                rows.append(
                    {
                        "Scenario": str(scenario),
                        "Sample_Size": int(sample_size),
                        "Statistic": statistic,
                        "Target": target[statistic],
                        "Exact_Expectation": observed[statistic],
                        "Absolute_Error": error,
                        "Tolerance": atol,
                        "Passed": bool(error <= atol),
                    }
                )
    return pd.DataFrame(rows)


def validate_golden_reference(
    path: str | Path | None = None,
    *,
    rtol: float = 1e-12,
    atol: float = 1e-14,
) -> pd.DataFrame:
    """Compare SNPio with a committed ``moments-popgen 1.6.0`` corpus."""

    fixture_path = (
        validation_data_path("moments_popgen_1_6_0_golden.csv.gz")
        if path is None
        else Path(path)
    )
    reference = pd.read_csv(fixture_path)
    required = {"case_id", *COUNT_COLUMNS, *STATISTICS}
    missing = required.difference(reference.columns)
    if missing:
        raise ValueError(f"Golden reference is missing columns: {sorted(missing)}")

    counts = reference.loc[:, COUNT_COLUMNS].to_numpy(dtype=np.int64)
    observed = evaluate_unbiased_ld(counts)
    rows = []
    for statistic in STATISTICS:
        expected = reference[statistic].to_numpy(dtype=np.float64)
        actual = observed[statistic]
        absolute_error = np.abs(actual - expected)
        tolerance = atol + rtol * np.abs(expected)
        for case_id, expected_value, actual_value, error, limit in zip(
            reference["case_id"], expected, actual, absolute_error, tolerance
        ):
            rows.append(
                {
                    "Case_ID": int(case_id),
                    "Statistic": statistic,
                    "Expected": expected_value,
                    "Observed": actual_value,
                    "Absolute_Error": error,
                    "Tolerance": limit,
                    "Passed": bool(error <= limit),
                }
            )
    return pd.DataFrame(rows)


def compare_published_estimates(
    observed: pd.DataFrame,
    *,
    relative_tolerance: float = 0.05,
) -> pd.DataFrame:
    """Compare SNPio island-fox estimates with published table 1 values."""

    required = {"Population", "Ne", "Ne_CI_Lower", "Ne_CI_Upper"}
    missing = required.difference(observed.columns)
    if missing:
        raise ValueError(f"Observed summary is missing columns: {sorted(missing)}")

    merged = PUBLISHED_ISLAND_FOX_ESTIMATES.merge(
        observed.loc[:, sorted(required)],
        on="Population",
        how="left",
        validate="one_to_one",
    )
    merged["Relative_Error"] = (merged["Ne"] - merged["Published_Ne"]).abs() / merged[
        "Published_Ne"
    ]
    merged["CI_Overlaps"] = (
        merged["Ne_CI_Upper"] >= merged["Published_Ne_CI_Lower"]
    ) & (merged["Ne_CI_Lower"] <= merged["Published_Ne_CI_Upper"])
    merged["Passed"] = (
        merged["Relative_Error"].le(relative_tolerance) & merged["CI_Overlaps"]
    )
    return merged


def summarize_convergence(results: pd.DataFrame) -> pd.DataFrame:
    """Summarize pair-subsampling stability by population and pair budget."""

    required = {"Population", "max_pairs", "seed", "r2D", "rDz", "Ne", "Pairs"}
    missing = required.difference(results.columns)
    if missing:
        raise ValueError(f"Convergence results are missing columns: {sorted(missing)}")

    metrics = ("r2D", "rDz", "Ne", "Pairs")
    summary = (
        results.groupby(["Population", "max_pairs"], dropna=False)[list(metrics)]
        .agg(["count", "mean", "std", "min", "max"])
        .reset_index()
    )
    summary.columns = [
        (
            "_".join(str(part) for part in column if str(part))
            if isinstance(column, tuple)
            else str(column)
        )
        for column in summary.columns
    ]
    for metric in ("r2D", "rDz", "Ne"):
        denominator = summary[f"{metric}_mean"].abs()
        summary[f"{metric}_CV"] = np.divide(
            summary[f"{metric}_std"],
            denominator,
            out=np.full(summary.shape[0], np.nan),
            where=denominator > 0.0,
        )
    return summary


__all__ = [
    "COUNT_COLUMNS",
    "DEFAULT_HAPLOTYPE_SCENARIOS",
    "PUBLISHED_ISLAND_FOX_ESTIMATES",
    "STATISTICS",
    "compare_published_estimates",
    "enumerate_count_vectors",
    "exact_multinomial_expectation",
    "genotype_probabilities_from_haplotypes",
    "population_ld_statistics",
    "prepare_island_fox_genepop",
    "summarize_convergence",
    "validate_exact_expectations",
    "validate_golden_reference",
    "validation_data_path",
]
