name: snpio-build
channels:
  - conda-forge
  - bioconda
  - defaults

channel_priority: flexible

dependencies:
  - python >=3.11,<3.13
  - pysam >=0.23.0
  - bokeh
  - h5py
  - holoviews
  - python-kaleido
  - kneed
  - matplotlib
  - multiqc >=1.29
  - numpy
  - numba
  - pandas
  - panel
  - plotly
  - requests
  - scikit-learn
  - scipy
  - statsmodels
  - seaborn
  - toytree
  - tqdm
