name: snpio-build
channels:
  - conda-forge
  - bioconda

channel_priority: strict

dependencies:
  - python >=3.11,<3.13
  - pysam >=0.23.0
  - bokeh
  - h5py
  - holoviews
  - python-kaleido >=0.2.1,<0.3
  - kneed
  - matplotlib
  - multiqc >=1.29
  - numpy >=1.26,<3
  - numba
  - pandas >=2.0,<3
  - panel
  - plotly >=5.18,<7
  - requests
  - scikit-learn
  - scipy
  - statsmodels
  - seaborn
  - toytree
  - tqdm
