{% set name = "snpio" %}
{% set version = "1.2.4" %}
{% set license = "GPL-3.0-or-later" %}
{% set github_url = "https://github.com/btmartin721/SNPio" %}

package:
    name: {{ name|lower }}
    version: "{{ version }}"

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 5720b6b20763608d7e913d4951ba5e1739625c4de893571cb4ccca911d3f293f

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python

requirements:
    host:
        - python >=3.11,<3.13
        - pip
    run:
        - python >=3.11,<3.13
        - bokeh
        - h5py
        - holoviews
        - python-kaleido
        - kneed
        - matplotlib
        - numpy
        - pandas
        - panel
        - plotly
        - pysam
        - requests
        - scikit-learn
        - scipy
        - statsmodels
        - seaborn
        - toytree
        - tqdm

test:
    imports:
        - snpio

about:
    home: {{ github_url }}
    license: {{ license }}
    license_family: GPL
    license_file: LICENSE
    summary: "SNPio is a Python API for population genetic file processing, filtering, and analysis. SNPio is designed to be a user-friendly tool for the manipulation of population genetic data in a variety of formats, including VCF, PHYLIP, and STRUCTURE files. SNPio can be used to filter data based on missing data, minor allele frequency, singletons, and monomorphic sites. SNPio can also be used to convert between file formats, and to generate summary statistics for population genetic analyses. SNPio is designed to be a flexible and user-friendly tool for the analysis of population genetic data."
    dev_url: {{ github_url }}
    doc_url: https://snpio.readthedocs.io/en/latest/
