# This GitHub Actions workflow runs tests on multiple Python versions
# whenever code is pushed to the main or master branches or a pull request is opened.
# It uses pytest to run the tests located in the 'tests/' directory.
# The workflow sets up Python versions 3.11 and 3.12, installs the package with its development dependencies,
# and runs the tests to ensure code quality and functionality.
# If any test fails, the workflow will report the failure, helping maintain code integrity.
name: CI Testing on Python Versions 3.11 and 3.12

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        run: pytest tests/