# Workflow name
name: Publish Conda Package

# Trigger the workflow on pushes to tags matching the pattern v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

# Define the jobs to be executed
jobs:
  build-and-upload:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: snpio-build
          miniforge-variant: Miniforge3
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          use-only-tar-bz2: true
          channels: bioconda,conda-forge
          channel-priority: strict
          auto-activate-base: false

      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          conda install -y conda-build anaconda-client

      - name: Build Conda package
        shell: bash -l {0}
        env:
          CI: "1"
        run: |
          conda config --set channel_priority strict
          conda config --remove-key channels || true
          conda config --add channels bioconda
          conda config --add channels conda-forge
          conda config --add channels defaults

          conda build recipe/ \
            --output-folder conda_build_artifacts \
            --python ${{ matrix.python-version }}

      - name: Upload to Anaconda.org
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        run: |
          anaconda -t $ANACONDA_API_TOKEN upload \
            conda_build_artifacts/**/snpio-*.tar.bz2 \
            --user btmartin721 --label main --force
