name: Publish Conda Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda (using Miniforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: snpio-build
          auto-activate-base: false
          installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
      
      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          # If using Mambaforge, it's good practice to use mamba for installations
          mamba install -y conda-build anaconda-client

      - name: Build Conda package
        shell: bash -l {0}
        env:
          CI: "1"
        run: |
          conda-build recipe/ \
            --output-folder conda_build_artifacts \
            --python ${{ matrix.python-version }}

      - name: Upload to Anaconda.org
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        run: |
          anaconda -t $ANACONDA_API_TOKEN upload \
            conda_build_artifacts/**/snpio-*.tar.bz2 \
            --user btmartin721 --label main --force