# Workflow name
name: Publish Conda Package

# Trigger the workflow on pushes to tags matching the pattern v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

# Define the jobs to be executed
jobs:
  build-and-upload:
    # Run the job on a matrix of operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      # Define the matrix of OS and Python versions
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11", "3.12", "3.13"]

    # Steps to be executed within the job
    steps:
      - name: Checkout code
        # Use the checkout action to get your repository code
        uses: actions/checkout@v4

      - name: Set up Conda (using Mambaforge for speed)
        # Use the setup-miniconda action to set up the Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Specify the Python version from the matrix
          python-version: ${{ matrix.python-version }}
          # Automatically update Conda itself
          auto-update-conda: true
          # Create and activate a specific environment for building
          activate-environment: snpio-build
          # Prefer Mambaforge for faster dependency solving and installation
          # Change to 'Miniforge' if you prefer standard conda
          miniforge-variant: Mambaforge
          # Force the use of .tar.bz2 packages (often preferred in CI)
          use-only-tar-bz2: true
          # Specify the channels to use, in order of priority
          channels: conda-forge,bioconda,defaults
          # Set channel priority to flexible
          channel-priority: flexible
          # Prevent auto-activation of the base environment
          auto-activate-base: false

      - name: Install conda-build and anaconda-client
        # Use a login bash shell to ensure the conda environment is sourced
        shell: bash -l {0}
        run: |
          # Use mamba install for faster installation if using Mambaforge
          # If you used miniforge-variant: Miniforge, use 'conda install' here
          mamba install -y conda-build anaconda-client

      - name: Build Conda package
        # Use a login bash shell
        shell: bash -l {0}
        env:
          # Set CI environment variable
          CI: "1"
        run: |
          # Build the conda package using the recipe in the 'recipe/' directory
          conda-build recipe/ \
            --output-folder conda_build_artifacts \
            --python ${{ matrix.python-version }} # Specify the Python version for the build

      - name: Upload to Anaconda.org
        # Use a login bash shell
        shell: bash -l {0}
        env:
          # Access the Anaconda API token from GitHub secrets
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        run: |
          # Upload the built package to Anaconda.org
          # -t $ANACONDA_API_TOKEN: Use the API token for authentication
          # conda_build_artifacts/**/snpio-*.tar.bz2: Pattern to find the built package files
          # --user btmartin721: Specify the Anaconda.org user
          # --label main: Specify the label (e.g., main, dev)
          # --force: Force upload, overwriting if the package already exists
          anaconda -t $ANACONDA_API_TOKEN upload \
            conda_build_artifacts/**/snpio-*.tar.bz2 \
            --user btmartin721 --label main --force
