# Workflow name
name: Publish Conda Package

# Trigger the workflow on pushes to tags matching the pattern v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

# Define the jobs to be executed
jobs:
  build-and-upload:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"
          activate-environment: snpio-build
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          environment-file: etc/environment.yml

      - name: Build Conda package
        shell: bash -el {0}
        env:
          CI: "1"
        run: |
          conda install --yes conda-build anaconda-client
          conda build recipe/ \
            --output-folder conda_build_artifacts \
            --python ${{ matrix.python-version }} --no-test

      - name: Upload to Anaconda.org
        shell: bash -el {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        run: |
          anaconda -t $ANACONDA_API_TOKEN upload \
            conda_build_artifacts/**/snpio-*.tar.bz2 \
            --user btmartin721 --label main --force
