name: Build and Publish Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: btmartin721/snpio

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            btmartin721/snpio:latest
            btmartin721/snpio:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Confirm success
        run: echo "Docker image pushed to Docker Hub!"
