name: Publish to TestPyPI and PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on tag pushes like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*
          echo "Package published to TestPyPI successfully."

      Uncomment the block below to enable PyPI publishing as well
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.SNPIO_API_TOKEN2_PYPI }}
        run: |
          twine upload dist/*
          echo "Package published to PyPI successfully."
