name: Publish to TestPyPI, PyPI, and Docker

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on semantic version tag pushes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'        

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Clean dist directory
        run: rm -rf dist/

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*
          echo "TestPyPI upload complete."

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.SNPIO_API_TOKEN2_PYPI }}
        run: |
          twine upload dist/*
          echo "Published to PyPI."

      ##########################################
      # Docker build and push after PyPI upload
      ##########################################

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BTMARTIN721 }}

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: btmartin721/snpio

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            btmartin721/snpio:latest
            btmartin721/snpio:${{ steps.extract_version.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Confirm Docker success
        run: echo "Docker image built for version ${{ steps.extract_version.outputs.VERSION }}"
